import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import LoginModal from "./components/modals/LoginModal";
import SingupModal from "./components/modals/SingupModal";
import AddPropertyModal from "./components/modals/AddPropertyModal";
import SearchModal from "./components/modals/SearchModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Django bnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = <p>Content</p>;
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="pt-32">{children}</div>
        <LoginModal />
        <SingupModal />
        <AddPropertyModal />
        <SearchModal />
      </body>
    </html>
  );
}
